name: Evo - Deploy by Push

on:
  push:
    branches:
      - "evo"

permissions:
  id-token: write
  contents: read

jobs:
  call_build:
    uses: ./.github/workflows/evo-build.yml
    secrets: inherit
